server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的服务名
  cloud:
    config:
      server:
        git:
          # gitHub上的仓库名称
          uri: git@github.com:ShuiShen-Li/springcloud-config.git
          ###搜索目录
          search-paths:
            - springcloud-config
        label: master



eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从Eurekaserver抓取已有的注册信息，默认为true，单点为所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka #集群
  instance:
      hostname: cloud-config-center
      prefer-ip-address: true #访问路径可以显示ip地址
